# YoutubeData

In [12]:
# Import required Libraries

import requests
import pandas as pd
import time

In [17]:
API_KEY = 'AIzaSyAuu0a4TErfms_diG_ZFGXuNAwvi3yQAiQ'

In [18]:
CHANNEL_ID = 'UCW8Ews7tdKKkBT6GdtQaXvQ'

In [19]:
# Function to get view_count, like_count and comment_count for each video.

def get_video_details(video_id):
    url_stats = 'https://youtube.googleapis.com/youtube/v3/videos?part=statistics&id='+video_id+'&key='+API_KEY
    response_stats = requests.get(url_stats).json()
        
    view_count = response_stats['items'][0]['statistics']['viewCount']
    like_count = response_stats['items'][0]['statistics']['likeCount']
    comment_count = response_stats['items'][0]['statistics']['commentCount']
    return view_count, like_count, comment_count

In [20]:
#Create an empty dataframe that will be fulfill with the data collected for each video.
df = pd.DataFrame(columns=["video_id","video_title","published_date","channel_title","channel_id","view_count","like_count","comment_count"])

In [21]:
#Create a dataframe with metrics included in get_video_details and also: video_id, video_title_published_date,
#channel_tittle and channel_id

pageToken = ""
while 1:
    url = "https://www.googleapis.com/youtube/v3/search?key="+API_KEY+"&channelId="+CHANNEL_ID+"&part=snippet,id&order=date&maxResults=10000&"+pageToken
    
    response = requests.get(url).json()
    time.sleep(1)
    for video in response['items']:
        if video ['id']['kind'] == 'youtube#video':
            video_id = video['id']['videoId']
            video_title = video['snippet']['title']
            published_date = video['snippet']['publishedAt']
            published_date = str(published_date).split("T")[0]
            channel_title = video['snippet']['channelTitle']
            channel_id = video['snippet']['channelId']
            view_count, like_count, comment_count = get_video_details(video_id)

            df2 = pd.DataFrame({"video_id": [video_id], "video_title": [video_title], "published_date": [published_date],"channel_title":[channel_title] ,"channel_id":[channel_id],"view_count":[view_count],"like_count": [like_count],"comment_count": [comment_count]})
            df = pd.concat([df, df2], ignore_index=True)
    try:
        if response['nextPageToken'] != None:
            pageToken = "pageToken=" + response['nextPageToken']
    except:
        break

In [22]:
#Columns data type
df.dtypes

video_id          object
video_title       object
published_date    object
channel_title     object
channel_id        object
view_count        object
like_count        object
comment_count     object
dtype: object

In [23]:
#How the new dataframe would look like.
df

,video_id,video_title,published_date,channel_title,channel_id,view_count,like_count,comment_count
0,cEannyn5exA,What Visualization Frameworks Do You Need To L...,2023-11-16,StrataScratch,UCW8Ews7tdKKkBT6GdtQaXvQ,611,28,1
1,tT7STcGCvUY,Cleaning Data Like a 10x Data Scientist,2023-11-08,StrataScratch,UCW8Ews7tdKKkBT6GdtQaXvQ,1385,71,2
2,O4FXdudaZAY,10 Ways Not To Suck On Coding Interviews For D...,2023-11-01,StrataScratch,UCW8Ews7tdKKkBT6GdtQaXvQ,734,23,0
3,q9HJ3hGjdo4,5 Skills Companies Look For in Data Science Ca...,2023-10-11,StrataScratch,UCW8Ews7tdKKkBT6GdtQaXvQ,1028,51,0
4,WS0fM1agxTk,Master SQL Subqueries with Multiple Tables,2023-09-20,StrataScratch,UCW8Ews7tdKKkBT6GdtQaXvQ,1718,54,4
...,...,...,...,...,...,...,...,...
174,UX4_IgagL9I,How to Use Google Colaboratory | Import a CSV ...,2020-05-02,StrataScratch,UCW8Ews7tdKKkBT6GdtQaXvQ,2654,16,2
175,tDdo3FiWpgE,Interview Questions for SQL Joins and Subqueries,2020-02-01,StrataScratch,UCW8Ews7tdKKkBT6GdtQaXvQ,1972,28,0
176,wW827gqxlRY,SQL Job Interview Mistakes #2,2019-09-15,StrataScratch,UCW8Ews7tdKKkBT6GdtQaXvQ,1201,20,0
177,xbc2GpGUXwc,SQL Job Interview Mistakes #1,2019-08-03,StrataScratch,UCW8Ews7tdKKkBT6GdtQaXvQ,8222,75,1
178,n6gM265zG68,SQL Query Interview Questions And Answers From...,2019-06-26,StrataScratch,UCW8Ews7tdKKkBT6GdtQaXvQ,44691,582,9

In [28]:
#Send dataframe to a csv file
df.to_csv('youtube_vids_2nd_pull.csv')